[package]
name = "zksync-sso-erc4337-ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "FFI bindings for zkSync SSO ERC-4337 (mobile platforms)"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
# Core dependency
zksync-sso-erc4337-core = { path = "../zksync-sso-erc4337-core" }

# Uniffi for FFI bindings
uniffi.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true

# Error handling
thiserror.workspace = true

# Logging/Tracing
tracing.workspace = true
tracing-subscriber.workspace = true
log.workspace = true

# Async
tokio.workspace = true
async-trait.workspace = true
futures.workspace = true

# Platform-specific logging
[target.'cfg(any(target_os = "android"))'.dependencies]
android_logger.workspace = true

[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
oslog.workspace = true
