[package]
name = "alloy-web-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "alloy-web-cli"
path = "src/main.rs"

[dependencies]
alloy-web-core = { path = "../alloy-web-core" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
eyre = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }

[dev-dependencies]
tempfile = "3.0"
