config:
  MD013:
    code_blocks: false
    line_length: 80
    tables: false
    headings: false # Allow long headings
  MD033: false
  MD024: false
  MD029: false
gitignore: true
ignores:
  - ".github/**/*.md"
  - "**/docs/**/*.md" # Skip strict line length for detailed documentation
