[profile.default]
src = 'smart-contracts'
out = 'zkout'
libs = ['node_modules']
solc_version = '0.8.30'
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = 'cancun'

[profile.zksync]
src = 'smart-contracts'
libs = ['node_modules']
fallback_oz = true
is_system = false
