[package]
name = "sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
money = { path = "../money" }

# Async
tokio.workspace = true
async-trait.workspace = true
futures.workspace = true

# Alloy
alloy.workspace = true
alloy-zksync.workspace = true

# signer
k256 = { version = "0.13", default-features = false, features = ["ecdsa"] }

# Passkey support
passkey-types.workspace = true
passkey-client.workspace = true
passkey.workspace = true
passkey-authenticator.workspace = true
public-suffix.workspace = true

rand.workspace = true
hex.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true

# Error handling
eyre.workspace = true

# passkey support
coset = "0.3"

# Hashing
sha2 = "0.10"
sha3 = "0.10.8"

# URL handling
url = { workspace = true, features = ["serde"] }

# CBOR
serde_cbor = "0.11"
ciborium = { version = "^0.2.1", default-features = false }
ciborium-io = { version = "^0.2.0", features = ["alloc"] }

# Base64
base64-url.workspace = true
base64.workspace = true

# DER
der = { version = "0.7", features = ["alloc"] }
der_derive = "0.7"

# Mocking
mockall = { version = "0.13.1" }
scopeguard = { version = "1.2.0" }

# Logging
log.workspace = true

[dev-dependencies]
