[package]
name = "sdk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
money = { path = "../money" }

# Async
tokio.workspace = true
async-trait.workspace = true
futures.workspace = true

# Alloy
alloy.workspace = true
alloy-zksync.workspace = true

# Signer
k256.workspace = true

# Passkey support
passkey-types.workspace = true
passkey-client.workspace = true
passkey.workspace = true
passkey-authenticator.workspace = true
public-suffix.workspace = true

# Randomness
rand.workspace = true

# Serialization
serde.workspace = true
serde_json.workspace = true

# Error handling
eyre.workspace = true

# Hashing
sha2.workspace = true
sha3.workspace = true

# URL handling
url = { workspace = true, features = ["serde"] }

# passkey support
coset.workspace = true

# CBOR
serde_cbor.workspace = true
ciborium.workspace = true
ciborium-io.workspace = true

# Base64
base64-url.workspace = true
base64.workspace = true

# DER
der.workspace = true
der_derive.workspace = true

# Logging
log.workspace = true

[dev-dependencies]
# Mocking
mockall.workspace = true
scopeguard.workspace = true
