[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Jack Pooley"]
license = "MIT"
homepage = "https://github.com/jackpooleyml/alloy-web"
repository = "https://github.com/jackpooleyml/alloy-web"

[workspace.dependencies]
# Alloy dependencies
alloy = { version = "1.0", default-features = false, features = [
    "rlp",
    "serde",
    "rpc-types",
    "rpc-types-eth",
    "signer-local",
    "contract",
    "provider-http",
    "reqwest",
    "network",
    "wasm-bindgen",
    "sol-types",
] }

# Core dependencies
tokio = { version = "1.38", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eyre = "0.6"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# CLI dependencies
clap = { version = "4.5", features = ["derive", "env"] }
dirs = "5.0"

# WASM dependencies
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
console_error_panic_hook = "0.1"
serde-wasm-bindgen = "0.6"

# HTTP client
reqwest = { version = "0.12", features = ["json"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
