[package]
name = "ffi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
uniffi = { workspace = true, features = ["cli", "tokio"] }
sdk = { path = "../sdk" }

# Serialization
serde.workspace = true
serde_json.workspace = true

# Async
tokio.workspace = true
futures.workspace = true
async-trait.workspace = true

# Error handling
eyre.workspace = true
thiserror.workspace = true

# Random bytes generation
rand.workspace = true
base64.workspace = true

# Hex encoding/decoding
hex.workspace = true

[build-dependencies]
uniffi = { workspace = true, features = ["build", "cli"] }
