name: "Preview Auth Server"
on:
  pull_request:
    paths:
      - "packages/erc4337-contracts/**"
      - "packages/sdk-platforms/rust/**"
      - "packages/auth-server/**"
      - "packages/sdk-4337/**"
  workflow_dispatch:

env:
  HUSKY: 0
  CI: true

jobs:
  build_and_preview:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    outputs:
      output_urls: "${{ steps.preview_deploy.outputs.urls }}"
    steps:
      - uses: actions/checkout@v4 # v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron
          cache: 'pnpm'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install dependencies
        run: pnpm install -r --frozen-lockfile

      # Web SDK depends on ERC-4337 contracts for WASM build
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1.5.0
        
      - name: Install ERC-4337 contract dependencies
        run: forge soldeer install
        working-directory: packages/erc4337-contracts

      - name: Build ERC-4337 contracts
        run: forge build
        working-directory: packages/erc4337-contracts

      - name: Build Auth Server
        env:
          NUXT_PUBLIC_CHAIN_ID: 8022833
          NUXT_PUBLIC_CHAIN_NAME: "ZKsyncOS Testnet"
          NUXT_PUBLIC_CHAIN_RPC_URL: "https://zksync-os-testnet-alpha.zksync.dev"
          NUXT_PUBLIC_BLOCK_EXPLORER_URL: "https://zksync-os-testnet-alpha.staging-scan-v2.zksync.dev"
          NUXT_PUBLIC_BLOCK_EXPLORER_API_URL: "https://block-explorer-api.zksync-os-testnet-alpha.zksync.dev/api"
          NUXT_PUBLIC_FACTORY_ADDRESS: "0x757b5c9854d327A6B76840c996dfAac0F6b3Dc1f"
          NUXT_PUBLIC_EOA_VALIDATOR_ADDRESS: "0x3497392f9662Da3de1EC2AfE8724CdBF6b884088"
          NUXT_PUBLIC_WEBAUTHN_VALIDATOR_ADDRESS: "0xa5C2c5C723239C0cD11a5691954CdAC4369C874b"
          NUXT_PUBLIC_SESSION_VALIDATOR_ADDRESS: "0x2bF3B894aA2C13A1545C6982bBbee435B5168b52"
          NUXT_PUBLIC_GUARDIAN_EXECUTOR_ADDRESS: "0x4337768cB3eC57Dd2cb843eFb929B773B13322de"
          NUXT_PUBLIC_BUNDLER_URL: "https://bundler-api.stage-sso.zksync.dev"
          NUXT_PUBLIC_BEACON_ADDRESS: "0x1D779D791B55a093dE60da664C3F301a87f96C62"
          NUXT_PUBLIC_AUTH_SERVER_API_URL: https://auth-server-api.stage-sso.zksync.dev
          NUXT_PUBLIC_SALT_SERVICE_URL: "https://sso-oidc.zksync.dev/salt"
        run: pnpm nx build auth-server

      - name: Deploy preview
        uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUTH_SERVER_STAGING }}"
          projectId: zksync-auth-server-staging
          target: zksync-auth-server-staging
